# Generated by Django 5.0.7 on 2024-07-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Enter a unique 3-character code for the city.",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="City Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the full name of the city.",
                        max_length=100,
                        verbose_name="City Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Enter a unique 5-character code for the hotel.",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Hotel Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the full name of the hotel.",
                        max_length=100,
                        verbose_name="Hotel Name",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Select the city where the hotel is located.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="hotel.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotels",
                "ordering": ["name"],
            },
        ),
    ]
